version: '3.7'

services:
  workspace:
    container_name: workspace
    restart: always
    image: thinhhung/laravel-workspace:7.3-oci8
    volumes:
      - ./:/var/www/laravel
    tty: true
  php-fpm:
    container_name: php-fpm
    restart: always
    image: thinhhung/laravel-php-fpm:7.3-oci8
    volumes:
      - ./:/var/www/laravel
    expose:
      - "9000"
    depends_on:
      - workspace
  nginx:
    container_name: nginx
    restart: always
    image: thinhhung/laravel-nginx:https
    volumes:
      - ./:/var/www/laravel
      - .docker/logs/nginx:/var/log/nginx
    ports:
      - "8000:80"
      - "8003:443"
    depends_on:
      - php-fpm
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/mysql:/var/lib/mysql
      - .docker/data:/data
  mysql_test:
    container_name: mysql_test
    restart: always
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/mysql_test:/var/lib/mysql
      - .docker/data_test:/data
  redis:
    container_name: redis
    restart: always
    image: redis
    expose:
      - "6379"
